alternative approach to removing ServerOptionsBuilderOptions
peterbom/azure-batch-software-entitlement pull request #2
Opened 2018-01-25 21:38 UTC by peterbom

Rather than changing the behaviour of the builder itself, I wanted to see if we can change the CertificateStore implementation so that it doesn't block testing.

2018-01-26 00:58 UTC, theunrepentantgeek requested changes
You've convinced me - this is really clean. 👍 
A few minor bits of cleanup.

Submit this as a PR to the main repo, I'll merge it, and abandon my spike.

2018-01-26 00:58 UTC, theunrepentantgeek commented on src/Microsoft.Azure.Batch.SoftwareEntitlement.Common/CertificateStore.cs
> +
Needs documentation comments - copy them from the implementation

2018-01-26 00:58 UTC, theunrepentantgeek commented on src/sestest/ServerOptionBuilder.cs
> +        public static Errorable<ServerOptions> Build(ServerCommandLine commandLine, ICertificateStore certificateStore)
I think we should get rid of the static method - it was there to hide `ServerOptionBuilderOptions.None`

2018-01-26 00:58 UTC, theunrepentantgeek commented on src/sestest/ServerOptionBuilder.cs
> +        private ServerOptionBuilder(ServerCommandLine commandLine, ICertificateStore certificateStore)
So this needs to become public.

2018-01-26 00:58 UTC, theunrepentantgeek commented on tests/Microsoft.Azure.Batch.SoftwareEntitlement.Tests/FakeCertificateStore.cs
> +        private readonly Dictionary<string, X509Certificate2> _certLookup;
Make this `Dictionary<CertificateThumbprint, X509Certificate2>` - the `CertificateThumbprint` struct implements `.Equals(object)` and `.GetHashCode()` properly, so it should work as a key for the Dictionary.

2018-01-26 00:58 UTC, theunrepentantgeek commented on tests/Microsoft.Azure.Batch.SoftwareEntitlement.Tests/FakeCertificateStore.cs
> +        }
This is traversing the dictionary's internal structures twice. Better this way:
```
if (_certLookup.TryGetValue(thumbprint out var certificate)) {
    return Errorable.Success(certificate);
}

return Errorable.Failure<X509Certificate2>(_notFoundError);
```

2018-01-26 00:58 UTC, theunrepentantgeek commented on tests/Microsoft.Azure.Batch.SoftwareEntitlement.Tests/ServerOptionBuilderTests.cs
> +        private readonly ICertificateStore _certificateStoreWithConnectionCertificate = new FakeCertificateStore(
I think we could call this `_certificateStore`.

2018-01-28 21:41 UTC, peterbom commented
Already merged as separate PR

2018-01-28 21:41 UTC, closed without merging